## local 환경
spring:
  config.activate.on-profile: local
  datasource:
    url: ${DB_RANKING_URL}
    username: ${DB_RANKING_USERNAME}
    password: ${DB_RANKING_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      # 더미데이터
#      data-locations: classpath:db/data.sql
