server:
  port: ${ALERT_SERVER}

spring:
  application:
    name: alert-service
  config:
    activate:
      on-profile: aws

  datasource:
    url: ${DB_ALERT_URL}
    username: ${DB_ALERT_USERNAME}
    password: ${DB_ALERT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    url: ${KAFKA_BOOTSTRAP_SERVERS}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      auto-offset-reset: earliest


slack:
  token: ${SLACK_BOT_TOKEN}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}