spring:
  application:
    name: user-service
  config:
    import:
      - file:.env[.properties]
      - classpath:./properties/datasource.yml
      - classpath:./properties/jpa.yml
  profiles:
    group:
      local: local, key
    active: ${ACTIVE_VAL}
  kafka:
    url: localhost:9092
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: user-group
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}  # Eureka 서버 URL
server:
  port: ${USER_SERVER}