spring:
  application:
    name: user-service
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:./properties/datasource.yml
      - classpath:./properties/jpa.yml
  profiles:
    active: local
  kafka:
    url: ${KAFKA_BOOTSTRAP_SERVERS}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      auto-offset-reset: earliest
      group-id: user-group
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER}
  instance:
    prefer-ip-address: true
server:
  port: ${USER_SERVER}
