spring:
  datasource:
    url: ${DB_USER_URL}
    username: ${DB_USER_USERNAME}
    password: ${DB_USER_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 20000
      auto-commit: false
  sql:
    init:
      mode: always
      # 더미데이터
#      data-locations: classpath:db/data.sql
